// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PetitsPains.Resources
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using PetitsPains.Model;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\00 - Data\programmation\PetitsPains\PetitsPains\Resources\EmailTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class EmailTemplate : EmailTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n<meta charset=\"UTF-8\">\r\n<title>Title of the docu" +
                    "ment</title>\r\n</head>\r\n\r\n<body>\r\n    <h1>Rapport en date du ");
            
            #line 15 "C:\00 - Data\programmation\PetitsPains\PetitsPains\Resources\EmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(date.ToString("d")));
            
            #line default
            #line hidden
            this.Write(@"</h1>
    <div style=""font-size:70%"">
        Légende :
        <ul>
            <li><img height=""12"" width=""12"" src=""cid:croissantEmpty"" alt=""Emplacement non utilisé"" title=""Emplacement non utilisé"" />&nbsp;: emplacement non utilisé ;</li>
            <li><img height=""12"" width=""12"" src=""cid:croissantFilled"" alt=""Pénalité"" title=""Pénalité"" />&nbsp;: emplacement avec une pénalité (la date de la pénalité s'affiche au survol) ;</li>
            <li><img height=""12"" width=""12"" src=""cid:croissantGreyed"" alt=""Emplacement désactivé"" title=""Emplacement désactivé"" />&nbsp;: emplacement désactivé.</li>
        </ul>
    </div>
    ");
            
            #line 24 "C:\00 - Data\programmation\PetitsPains\PetitsPains\Resources\EmailTemplate.tt"

    var peopleThatGotAPenalty = (from line in lines
                                where line.PenaltiesAdded.Count > 0
                                select line.Person).ToList();

    var peopleThatHaveToBringCroissants =   (from line in lines
                                            where line.HasToBringCroissants
                                            select line.Person).ToList();

    if (peopleThatGotAPenalty.Count > 0)
    {
        // TODO: generate the message to indicate that a list of people got at last 1 penalty this time.
        
            
            #line default
            #line hidden
            this.Write("<div></div>");
            
            #line 36 "C:\00 - Data\programmation\PetitsPains\PetitsPains\Resources\EmailTemplate.tt"

    }
    else
    {
        // TODO: generate the message to indicate that no one got a penalty.
        
            
            #line default
            #line hidden
            this.Write("<div>\r\n        Aucun oublie de CRA ce jour.\r\n    </div>\r\n");
            
            #line 44 "C:\00 - Data\programmation\PetitsPains\PetitsPains\Resources\EmailTemplate.tt"

    }

    if (peopleThatHaveToBringCroissants.Count > 0)
    {
        // TODO: generate the message to indicate that a list of people has to bring the croissants.
    }
    
            
            #line default
            #line hidden
            this.Write("    <table>\r\n    ");
            
            #line 53 "C:\00 - Data\programmation\PetitsPains\PetitsPains\Resources\EmailTemplate.tt"

    int length = lines.Count();
    for (int i = 0; i < length; i++)
    {
        
            
            #line default
            #line hidden
            this.Write("    <tr>\r\n            <td style=\"margin:0 20px 0 0\">");
            
            #line 58 "C:\00 - Data\programmation\PetitsPains\PetitsPains\Resources\EmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lines[i].Person.ToString()));
            
            #line default
            #line hidden
            this.Write("</td>\r\n");
            
            #line 59 "C:\00 - Data\programmation\PetitsPains\PetitsPains\Resources\EmailTemplate.tt"

        foreach (var croissant in lines[i].Croissants)
        {
            if (croissant.State == Croissant.CroissantState.IsAvailable)
            {
                        
            
            #line default
            #line hidden
            this.Write("            <td><img height=\"16\" width=\"16\" src=\"cid:croissantEmpty\" alt=\"Emplace" +
                    "ment non utilisé\" title=\"Emplacement non utilisé\" /></td>\r\n");
            
            #line 65 "C:\00 - Data\programmation\PetitsPains\PetitsPains\Resources\EmailTemplate.tt"

            }
            else if (croissant.State == Croissant.CroissantState.IsUsed)
            {
                        
            
            #line default
            #line hidden
            this.Write("            <td><img height=\"16\" width=\"16\" src=\"cid:croissantFilled\" alt=\"Pénali" +
                    "té en date du ");
            
            #line 69 "C:\00 - Data\programmation\PetitsPains\PetitsPains\Resources\EmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(croissant.Date.Value.ToString("d")));
            
            #line default
            #line hidden
            this.Write("\" title=\"Pénalité en date de ");
            
            #line 69 "C:\00 - Data\programmation\PetitsPains\PetitsPains\Resources\EmailTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(croissant.Date.Value.ToString("d")));
            
            #line default
            #line hidden
            this.Write("\" /></td>\r\n");
            
            #line 70 "C:\00 - Data\programmation\PetitsPains\PetitsPains\Resources\EmailTemplate.tt"

            }
            else if (croissant.State == Croissant.CroissantState.IsDeactivated)
            {
                        
            
            #line default
            #line hidden
            this.Write("            <td><img height=\"16\" width=\"16\" src=\"cid:croissantGreyed\" alt=\"Emplac" +
                    "ement désactivé\" title=\"Emplacement désactivé\" /></td>\r\n");
            
            #line 75 "C:\00 - Data\programmation\PetitsPains\PetitsPains\Resources\EmailTemplate.tt"

            }
        }

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 79 "C:\00 - Data\programmation\PetitsPains\PetitsPains\Resources\EmailTemplate.tt"


        // Only for indentation purpose
        if (i == (length - 1))
        {
            
            
            #line default
            #line hidden
            this.Write("    </tr>\r\n");
            
            #line 85 "C:\00 - Data\programmation\PetitsPains\PetitsPains\Resources\EmailTemplate.tt"

        }
        else
        {
            
            
            #line default
            #line hidden
            this.Write("    </tr>\r\n    ");
            
            #line 90 "C:\00 - Data\programmation\PetitsPains\PetitsPains\Resources\EmailTemplate.tt"

        }
    }

            
            #line default
            #line hidden
            this.Write(@"    </table>
    <div style=""margin:20px 0 0 0"">
        Rappel des règles :
        <ul>
            <li>le CRA est à soumettre chaque jour de présence avant de partir ;</li>
            <li>le relevé des CRA se fait le matin ;</li>
            <li>du lundi au jeudi, si le CRA du jour précédent est manquant, la personne a une pénalité d'un croissant ;</li>
            <li>le vendredi et le lundi, s'il manque un CRA des jours précédents, la personne a une pénalité de deux croissants ;</li>
            <li>si la personne n'a pas saisie sont CRA de la semaine, elle a une pénalité « foutage de gueule » d'un croissant ;</li>
            <li>si une personne complète sa ligne, elle doit ramener croissants/petits pains/gâteau à l'équipe ET sa ligne est amputée d'une case.</li>
        </ul>
    </div>
</body>

</html> ");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class EmailTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
